image: node:8.12.0-alpine

cache:
    paths:
        - node_modules/

variables:
    AWS_DEFAULT_REGION: eu-west-2
    FACEBOOK_CLIENT_ID: 724818008039885
    BUCKET_NAME: frontend.cicd
    GOOGLE_CLIENT_ID: 854648413334-hiia36vlrq2c13m357jo4tgraho43h88.apps.googleusercontent.
    VUE_APP_API_URL: https://chaka.io
    VUE_APP_CRYPTO_KEY: chakadev
    VUE_APP_ISW_REF: 8lqZIapXMg
    VUE_APP_ISW_URL: https://qa.interswitchng.com/paymentgateway/public/js/webpay.js
    VUE_APP_MONNIFY_CONTRACT_CODE: 434994171518
    VUE_APP_MONNIFY_KEY: MK_PROD_74GGAWLUEB
    VUE_APP_MONNIFY_TEST_MODE: "false"
    VUE_APP_PAYSTACK_KEY: pk_live_815a9359387e1bace2719fb1a855c937d201eb58


stages:
    - build
    - deploy

build:
    stage: build
    variables:
        VUE_APP_ROUTER_BASE: ${CI_COMMIT_REF_SLUG}/${CI_COMMIT_SHA}
    script:
        - npm install
        - npm rebuild node-sass
        - npm run build
    artifacts:
        paths:
            - dist/
        expire_in: 1 hour
    only:
        - production
    except:
        - master

deploy_review:
    image: python:latest
    stage: deploy
    dependencies:
        - build
    script:
        - pip install awscli
        - aws s3 cp dist s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG}/${CI_COMMIT_SHA} --recursive
    environment:
        name: production/${CI_COMMIT_REF_SLUG}
        url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_COMMIT_REF_SLUG}/${CI_COMMIT_SHA}
        on_stop: remove_s3
    only:
        - production
    except:
        - master

remove_s3:
    image: python:latest
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - pip install awscli
        - aws s3 rm s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
    environment:
        name: production/${CI_COMMIT_REF_SLUG}
        action: stop
    when: manual

build_prod:
    stage: build
    before_script:
        - npm install
    script:
        - npm rebuild node-sass
        - npm run build
    artifacts:
        paths:
            - dist/
    only:
        - production

deploy_production:
    image: python:latest
    stage: deploy
    dependencies:
        - build
    before_script:
        - pip install awscli -q
    script:
        - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        - aws s3 cp dist s3://${BUCKET_NAME}/ --recursive
        - aws s3 cp s3://${BUCKET_NAME}/ s3://${BUCKET_NAME}/ --metadata-directive REPLACE --recursive --cache-control max-age=3600
        - aws s3 sync ./dist s3://${BUCKET_NAME} --acl public-read
    environment:
        name: production/${CI_COMMIT_REF_SLUG}
        url: https://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/production
    only:
        - production
