image: node:8.12.0-alpine

cache:
  paths:
    - node_modules/

variables:
  AWS_DEFAULT_REGION: eu-west-2
  BUCKET_NAME: gitcli.yml

stages:
  - build
  - deploy

build:
  stage: build
  variables:
    VUE_APP_ROUTER_BASE: ${CI_COMMIT_REF_SLUG}/${CI_COMMIT_SHA} 
  script:
   - npm install
   - npm rebuild node-sass
   - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - dev
  except:
    - master    

deploy_review:
  image: python:latest
  stage: deploy
  dependencies:
    - build
  script:
    - pip install awscli
    - aws s3 cp dist s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG}/${CI_COMMIT_SHA} --recursive
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    url: https://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_COMMIT_REF_SLUG}/${CI_COMMIT_SHA}
    on_stop: remove_s3
  only:
    - dev
  except:
    - master

remove_s3:
  image: python:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - pip install awscli
    - aws s3 rm s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  when: manual

build_prod:
  stage: build
  before_script:
   - npm install
  script:
   - npm rebuild node-sass
   - npm run build
  artifacts:
    paths:
      - dist/
  only:
   - dev     

deploy_production:
  image: python:latest
  stage: deploy
  dependencies:
    - build_prod
  before_script:
    - pip install awscli -q
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 cp dist s3://${BUCKET_NAME}/ --recursive
    - aws s3 cp s3://${BUCKET_NAME}/ s3://${BUCKET_NAME}/ --metadata-directive REPLACE --recursive --cache-control max-age=604800
    - aws s3 sync ./dist s3://${BUCKET_NAME} --acl public-read
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    url: https://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/dev
  only:
   - dev 
